### ISSUE TITLE
wasm.transactionSignWithDevice () fails with "RuntimeError: unreachable"

### ISSUE THREAD

**Issue by popra** [Zondax/filecoin-signing-tools#254] opened 2020-08-12 09:56 UTC
Hello,

calling `wasm.transactionSignWithDevice()` into a ledger nano S fails with "RuntimeError: unreachable" on 0.6.3:

![image](https://user-images.githubusercontent.com/5417511/90002072-d97acf00-dc9a-11ea-88bf-40e179a316a2.png)

the same message, serialized with `transactionSerialize()`, is successfully signed with `transactionSignRawWithDevice()`

**Comment by jleni** [comment] 2020-09-14 23:55
Yes, we are aware of this problem.
This is related to https://github.com/Zondax/filecoin-signing-tools/issues/205

At this moment, we would recommend using the pure js lib:

https://github.com/Zondax/ledger-filecoin-js
https://www.npmjs.com/package/@zondax/ledger-filecoin

**Comment by jleni** [comment] 2020-09-14 23:56
Closing as a duplicate of #205

**Closed by jleni** 2020-09-14 23:56 UTC
