### ISSUE TITLE
An error when transfer money from f4 address to f1 address

### ISSUE THREAD

**Issue by codeFarmL** [Zondax/filecoin-signing-tools#974] opened 2023-04-26 10:34 UTC
Transfer from f4 address to f1 address

Error signing transaction: Error: `Unknown signing protocol`

Is it currently supported?

:link: [zboto Link](https://app.clickup.com/t/8677x6qtn)

**Comment by rllola** [comment] 2023-09-12 09:20
It is supposed to be supported. I have added a test to be sure it is working as intended and it is passing.

Are you still facing this issue ? (closing this for now. Will re-open if you confirm it is still an issue.)

**Closed by rllola** 2023-09-12 09:20 UTC
