### ISSUE TITLE
Build issues in dev

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-signing-tools#348] opened 2021-01-06 19:20 UTC

**Comment by rllola** [comment] 2021-01-07 12:54
I am still trying to debug this. Here what I have so far...

The error : 
```
Module not found: Error: Can't resolve 'env'
```
The .js file seems to try to import an unknown `env` module. I have found a similar error in this issue in the wasm-bindgen repo https://github.com/rustwasm/wasm-bindgen/issues/2317

We haven't add any new library so it is unclear where it would be come from beside from a update in a dependency as we don't commit the Cargo.lock file. It was actually working locally for me when I had the cargo.lock file in the repo. I deleted to try reproduce the error seen in the CI. I have since not have been able to compile correctly the lib.

**Comment by rllola** [comment] 2021-01-09 10:07
This is fixed now.

**Closed by rllola** 2021-01-09 10:07 UTC
